name: Build Clippy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    env:
      Solution_Name: Clippy.sln
      Configuration: Release
      Platform: x64
      TargetPlatformVersion: 10.0.22621.0
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Add CommunityToolkit Labs NuGet source
      run: |
        dotnet nuget add source https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json --name CommunityToolkit-Labs
      
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name -Source "https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json"
      
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name
      
    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:AppxBundle=Never /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxPackageSigningEnabled=false /p:TargetPlatformVersion=$env:TargetPlatformVersion
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Clippy-Build-${{ github.sha }}
        path: |
          **/bin/${{ env.Configuration }}/**/*.exe
          **/bin/${{ env.Configuration }}/**/*.dll
          **/AppPackages/**
        retention-days: 30

  # Опциональный job для создания MSIX пакета
  package:
    runs-on: windows-2022
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    
    env:
      Solution_Name: Clippy.sln
      Configuration: Release
      Platform: x64
      TargetPlatformVersion: 10.0.22621.0
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Add CommunityToolkit Labs NuGet source
      run: |
        dotnet nuget add source https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json --name CommunityToolkit-Labs
      
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name -Source "https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json"
      
    - name: Build and Package
      run: |
        msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:AppxBundle=Always /p:AppxBundlePlatforms=$env:Platform /p:UapAppxPackageBuildMode=SideloadOnly /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=false /p:TargetPlatformVersion=$env:TargetPlatformVersion
        
    - name: Upload MSIX Package
      uses: actions/upload-artifact@v4
      with:
        name: Clippy-MSIX-Package
        path: |
          **/AppPackages/**/*.msix
          **/AppPackages/**/*.msixbundle
        retention-days: 90
